"""Galactic Diplomacy — blocs, resolutions, emergency, personality (GC-721B+)."""

from .blocs import (
    clear_alliance_bloc,
    get_alliance_bloc,
    list_alliance_blocs_for_galaxy,
    normalize_galaxy,
    set_alliance_bloc,
)
from .banner import build_galactic_diplomacy_banner
from .mechanics import (
    get_galaxy_diplomacy_mechanics,
    merge_diplomacy_mechanics,
)
from .emergencies import (
    EMERGENCY_KEYS,
    clear_active_emergency,
    get_active_emergency,
    get_emergency_definition,
    list_active_emergencies,
    list_emergency_definitions,
    normalize_emergency_key,
    reload_emergency_definitions,
    set_active_emergency,
)
from .resolutions import (
    RESOLUTION_KEYS,
    clear_active_resolution,
    get_active_resolution,
    get_resolution_definition,
    list_active_resolutions,
    list_resolution_definitions,
    normalize_resolution_key,
    reload_resolution_definitions,
    set_active_resolution,
)
from .personality import (
    ensure_galaxy_personality_state,
    get_galaxy_personality,
    infer_personality_key,
    score_directive_history,
    set_galaxy_personality,
)
from .definitions import (
    BLOC_KEYS,
    PERSONALITY_KEYS,
    get_bloc_definition,
    get_personality_definition,
    list_bloc_definitions,
    list_personality_definitions,
    normalize_bloc_key,
    normalize_personality_key,
    reload_definitions,
    schema_ready,
)

__all__ = [
    "BLOC_KEYS",
    "EMERGENCY_KEYS",
    "PERSONALITY_KEYS",
    "RESOLUTION_KEYS",
    "build_galactic_diplomacy_banner",
    "clear_active_emergency",
    "clear_active_resolution",
    "clear_alliance_bloc",
    "ensure_galaxy_personality_state",
    "get_active_emergency",
    "get_active_resolution",
    "get_alliance_bloc",
    "get_bloc_definition",
    "get_galaxy_personality",
    "get_galaxy_diplomacy_mechanics",
    "get_personality_definition",
    "get_emergency_definition",
    "get_resolution_definition",
    "infer_personality_key",
    "list_active_emergencies",
    "list_active_resolutions",
    "list_alliance_blocs_for_galaxy",
    "list_bloc_definitions",
    "list_personality_definitions",
    "list_emergency_definitions",
    "list_resolution_definitions",
    "merge_diplomacy_mechanics",
    "normalize_bloc_key",
    "normalize_emergency_key",
    "normalize_galaxy",
    "normalize_personality_key",
    "normalize_resolution_key",
    "reload_definitions",
    "reload_emergency_definitions",
    "reload_resolution_definitions",
    "schema_ready",
    "score_directive_history",
    "set_active_emergency",
    "set_active_resolution",
    "set_alliance_bloc",
    "set_galaxy_personality",
]
